--------------------------------------------------------------------------------
--  GROCERY MANAGEMENT SYSTEM  -  Database script for Oracle APEX
--------------------------------------------------------------------------------
--  How to run:
--    APEX > SQL Workshop > SQL Scripts > Create (or Upload) > paste this file
--    > Save > Run.  Check the results page: every statement should succeed.
--
--  Requires Oracle Database 12c or later (identity columns).
--  Works on apex.oracle.com and Oracle Autonomous Database.
--
--  Contents
--    Section 0  Optional cleanup (for re-running the script)
--    Section 1  Tables with primary keys, foreign keys, NOT NULL and CHECK
--    Section 2  Indexes on foreign key columns
--    Section 3  Stock package (PL/SQL used by the triggers and APEX)
--    Section 4  Triggers: auto Total Amount + stock increase / decrease
--    Section 5  Report views
--    Section 6  Sample data
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- SECTION 0 : OPTIONAL CLEANUP
-- Remove the /* and */ below if you want to drop everything and start again.
--------------------------------------------------------------------------------
/*
DROP VIEW  grocery_daily_sales_v;
DROP VIEW  grocery_sale_v;
DROP VIEW  grocery_purchase_v;
DROP VIEW  grocery_product_v;
DROP TABLE grocery_sale      PURGE;
DROP TABLE grocery_purchase  PURGE;
DROP TABLE grocery_product   PURGE;
DROP TABLE grocery_customer  PURGE;
DROP TABLE grocery_supplier  PURGE;
DROP TABLE grocery_category  PURGE;
DROP PACKAGE grocery_stock_pkg;
*/


--------------------------------------------------------------------------------
-- SECTION 1 : TABLES
-- "GENERATED BY DEFAULT ON NULL AS IDENTITY" creates the primary key value
-- automatically (Oracle manages a hidden sequence for you). APEX forms work
-- with it out of the box.
--------------------------------------------------------------------------------

-- 1.1 Categories -------------------------------------------------------------
CREATE TABLE grocery_category (
    category_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_name   VARCHAR2(100)  NOT NULL,
    description     VARCHAR2(400),
    CONSTRAINT grocery_category_pk      PRIMARY KEY (category_id),
    CONSTRAINT grocery_category_name_uk UNIQUE (category_name)
);

-- 1.2 Suppliers --------------------------------------------------------------
CREATE TABLE grocery_supplier (
    supplier_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    supplier_name   VARCHAR2(150)  NOT NULL,
    phone           VARCHAR2(15)   NOT NULL,
    email           VARCHAR2(150),
    address         VARCHAR2(400),
    CONSTRAINT grocery_supplier_pk       PRIMARY KEY (supplier_id),
    CONSTRAINT grocery_supplier_name_uk  UNIQUE (supplier_name),
    CONSTRAINT grocery_supplier_phone_ck CHECK (REGEXP_LIKE(phone, '^[0-9+ -]{7,15}$')),
    CONSTRAINT grocery_supplier_email_ck CHECK (email IS NULL OR REGEXP_LIKE(email, '^[^@ ]+@[^@ ]+\.[^@ ]+$'))
);

-- 1.3 Customers --------------------------------------------------------------
CREATE TABLE grocery_customer (
    customer_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_name   VARCHAR2(150)  NOT NULL,
    phone           VARCHAR2(15)   NOT NULL,
    email           VARCHAR2(150),
    address         VARCHAR2(400),
    CONSTRAINT grocery_customer_pk       PRIMARY KEY (customer_id),
    CONSTRAINT grocery_customer_phone_ck CHECK (REGEXP_LIKE(phone, '^[0-9+ -]{7,15}$')),
    CONSTRAINT grocery_customer_email_ck CHECK (email IS NULL OR REGEXP_LIKE(email, '^[^@ ]+@[^@ ]+\.[^@ ]+$'))
);

-- 1.4 Products ---------------------------------------------------------------
CREATE TABLE grocery_product (
    product_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_name    VARCHAR2(150)  NOT NULL,
    category_id     NUMBER         NOT NULL,
    supplier_id     NUMBER         NOT NULL,
    unit            VARCHAR2(20)   NOT NULL,
    purchase_price  NUMBER(10,2)   NOT NULL,
    selling_price   NUMBER(10,2)   NOT NULL,
    qty_in_stock    NUMBER(10)     DEFAULT ON NULL 0        NOT NULL,
    reorder_level   NUMBER(10)     DEFAULT ON NULL 10       NOT NULL,
    expiry_date     DATE,
    status          VARCHAR2(10)   DEFAULT ON NULL 'ACTIVE' NOT NULL,
    CONSTRAINT grocery_product_pk         PRIMARY KEY (product_id),
    CONSTRAINT grocery_product_name_uk    UNIQUE (product_name),
    CONSTRAINT grocery_product_cat_fk     FOREIGN KEY (category_id)
                                          REFERENCES grocery_category (category_id),
    CONSTRAINT grocery_product_sup_fk     FOREIGN KEY (supplier_id)
                                          REFERENCES grocery_supplier (supplier_id),
    CONSTRAINT grocery_product_unit_ck    CHECK (unit IN ('KG','GRAM','LITRE','ML','PACK','PIECE','BOTTLE','DOZEN')),
    CONSTRAINT grocery_product_pprice_ck  CHECK (purchase_price > 0),
    -- Business rule: selling price >= purchase price
    CONSTRAINT grocery_product_price_ck   CHECK (selling_price >= purchase_price),
    -- Business rule: quantity cannot be negative
    CONSTRAINT grocery_product_qty_ck     CHECK (qty_in_stock >= 0),
    CONSTRAINT grocery_product_reorder_ck CHECK (reorder_level >= 0),
    CONSTRAINT grocery_product_status_ck  CHECK (status IN ('ACTIVE','INACTIVE'))
);

-- 1.5 Purchases (stock coming IN from suppliers) -----------------------------
CREATE TABLE grocery_purchase (
    purchase_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    purchase_date   DATE           DEFAULT ON NULL SYSDATE NOT NULL,
    supplier_id     NUMBER         NOT NULL,
    product_id      NUMBER         NOT NULL,
    quantity        NUMBER(10)     NOT NULL,
    purchase_price  NUMBER(10,2)   NOT NULL,   -- defaults from product if left empty
    total_amount    NUMBER(12,2)   NOT NULL,   -- always calculated by trigger
    CONSTRAINT grocery_purchase_pk          PRIMARY KEY (purchase_id),
    CONSTRAINT grocery_purchase_sup_fk      FOREIGN KEY (supplier_id)
                                            REFERENCES grocery_supplier (supplier_id),
    CONSTRAINT grocery_purchase_product_fk  FOREIGN KEY (product_id)
                                            REFERENCES grocery_product (product_id),
    CONSTRAINT grocery_purchase_qty_ck      CHECK (quantity > 0),
    CONSTRAINT grocery_purchase_price_ck    CHECK (purchase_price > 0)
);

-- 1.6 Sales (stock going OUT to customers) -----------------------------------
CREATE TABLE grocery_sale (
    sale_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sale_date       DATE           DEFAULT ON NULL SYSDATE NOT NULL,
    customer_id     NUMBER         NOT NULL,
    product_id      NUMBER         NOT NULL,
    quantity        NUMBER(10)     NOT NULL,
    selling_price   NUMBER(10,2)   NOT NULL,   -- defaults from product if left empty
    total_amount    NUMBER(12,2)   NOT NULL,   -- always calculated by trigger
    CONSTRAINT grocery_sale_pk          PRIMARY KEY (sale_id),
    CONSTRAINT grocery_sale_cust_fk     FOREIGN KEY (customer_id)
                                        REFERENCES grocery_customer (customer_id),
    CONSTRAINT grocery_sale_product_fk  FOREIGN KEY (product_id)
                                        REFERENCES grocery_product (product_id),
    CONSTRAINT grocery_sale_qty_ck      CHECK (quantity > 0),
    CONSTRAINT grocery_sale_price_ck    CHECK (selling_price > 0)
);


--------------------------------------------------------------------------------
-- SECTION 2 : INDEXES ON FOREIGN KEY COLUMNS (faster joins and deletes)
--------------------------------------------------------------------------------
CREATE INDEX grocery_product_cat_idx   ON grocery_product  (category_id);
CREATE INDEX grocery_product_sup_idx   ON grocery_product  (supplier_id);
CREATE INDEX grocery_purchase_sup_idx  ON grocery_purchase (supplier_id);
CREATE INDEX grocery_purchase_prd_idx  ON grocery_purchase (product_id);
CREATE INDEX grocery_sale_cust_idx     ON grocery_sale     (customer_id);
CREATE INDEX grocery_sale_prd_idx      ON grocery_sale     (product_id);


--------------------------------------------------------------------------------
-- SECTION 3 : STOCK PACKAGE
-- All stock changes go through ADJUST_STOCK, so the "never below zero" rule
-- lives in exactly one place.
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE grocery_stock_pkg AS

    -- Returns current stock of a product (0 if not found)
    FUNCTION get_stock (p_product_id IN NUMBER) RETURN NUMBER;

    -- Adds p_change to stock (use a negative number to reduce stock).
    -- Raises ORA-20001 if stock would become negative.
    PROCEDURE adjust_stock (p_product_id IN NUMBER, p_change IN NUMBER);

END grocery_stock_pkg;
/

CREATE OR REPLACE PACKAGE BODY grocery_stock_pkg AS

    FUNCTION get_stock (p_product_id IN NUMBER) RETURN NUMBER IS
        l_qty grocery_product.qty_in_stock%TYPE;
    BEGIN
        SELECT qty_in_stock
          INTO l_qty
          FROM grocery_product
         WHERE product_id = p_product_id;
        RETURN l_qty;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END get_stock;


    PROCEDURE adjust_stock (p_product_id IN NUMBER, p_change IN NUMBER) IS
        l_qty   grocery_product.qty_in_stock%TYPE;
        l_name  grocery_product.product_name%TYPE;
    BEGIN
        -- Lock the product row so two users cannot sell the same stock at once
        SELECT qty_in_stock, product_name
          INTO l_qty, l_name
          FROM grocery_product
         WHERE product_id = p_product_id
           FOR UPDATE;

        IF l_qty + p_change < 0 THEN
            RAISE_APPLICATION_ERROR(-20001,
                'Not enough stock for ' || l_name ||
                '. Available: ' || l_qty ||
                ', required: '  || ABS(p_change) || '.');
        END IF;

        UPDATE grocery_product
           SET qty_in_stock = qty_in_stock + p_change
         WHERE product_id = p_product_id;
    END adjust_stock;

END grocery_stock_pkg;
/


--------------------------------------------------------------------------------
-- SECTION 4 : TRIGGERS
-- These fire for EVERY insert/update/delete - from APEX forms, interactive
-- grids, SQL Workshop or scripts - so stock is always correct.
--   * Price is copied from the product if not entered
--   * TOTAL_AMOUNT = QUANTITY x PRICE
--   * Purchase  -> stock goes UP
--   * Sale      -> stock goes DOWN (blocked if insufficient)
--   * Editing or deleting a record reverses its old effect first
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER grocery_purchase_biud
BEFORE INSERT OR UPDATE OR DELETE ON grocery_purchase
FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        IF :NEW.purchase_price IS NULL THEN
            SELECT purchase_price
              INTO :NEW.purchase_price
              FROM grocery_product
             WHERE product_id = :NEW.product_id;
        END IF;
        :NEW.total_amount := :NEW.quantity * :NEW.purchase_price;
    END IF;

    IF UPDATING AND :OLD.product_id = :NEW.product_id THEN
        -- same product, only quantity changed: apply the difference
        grocery_stock_pkg.adjust_stock(:NEW.product_id, :NEW.quantity - :OLD.quantity);
    ELSE
        IF UPDATING OR DELETING THEN
            grocery_stock_pkg.adjust_stock(:OLD.product_id, -:OLD.quantity);  -- undo old purchase
        END IF;
        IF INSERTING OR UPDATING THEN
            grocery_stock_pkg.adjust_stock(:NEW.product_id,  :NEW.quantity);  -- add new purchase
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER grocery_sale_biud
BEFORE INSERT OR UPDATE OR DELETE ON grocery_sale
FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        IF :NEW.selling_price IS NULL THEN
            SELECT selling_price
              INTO :NEW.selling_price
              FROM grocery_product
             WHERE product_id = :NEW.product_id;
        END IF;
        :NEW.total_amount := :NEW.quantity * :NEW.selling_price;
    END IF;

    IF UPDATING AND :OLD.product_id = :NEW.product_id THEN
        grocery_stock_pkg.adjust_stock(:NEW.product_id, :OLD.quantity - :NEW.quantity);
    ELSE
        IF UPDATING OR DELETING THEN
            grocery_stock_pkg.adjust_stock(:OLD.product_id,  :OLD.quantity);  -- return old sale to stock
        END IF;
        IF INSERTING OR UPDATING THEN
            grocery_stock_pkg.adjust_stock(:NEW.product_id, -:NEW.quantity);  -- take new sale from stock
        END IF;
    END IF;
END;
/


--------------------------------------------------------------------------------
-- SECTION 5 : REPORT VIEWS
-- Views join the IDs to readable names so APEX reports stay simple.
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW grocery_product_v AS
SELECT p.product_id,
       p.product_name,
       c.category_name,
       s.supplier_name,
       p.unit,
       p.purchase_price,
       p.selling_price,
       p.qty_in_stock,
       p.reorder_level,
       p.qty_in_stock * p.purchase_price             AS stock_value,
       p.expiry_date,
       p.status,
       CASE
           WHEN p.qty_in_stock = 0                THEN 'OUT OF STOCK'
           WHEN p.qty_in_stock <= p.reorder_level THEN 'LOW STOCK'
           ELSE 'OK'
       END                                           AS stock_status,
       p.category_id,
       p.supplier_id
  FROM grocery_product  p
  JOIN grocery_category c ON c.category_id = p.category_id
  JOIN grocery_supplier s ON s.supplier_id = p.supplier_id;

CREATE OR REPLACE VIEW grocery_purchase_v AS
SELECT pu.purchase_id,
       pu.purchase_date,
       s.supplier_name,
       p.product_name,
       p.unit,
       pu.quantity,
       pu.purchase_price,
       pu.total_amount,
       pu.supplier_id,
       pu.product_id
  FROM grocery_purchase pu
  JOIN grocery_supplier s ON s.supplier_id = pu.supplier_id
  JOIN grocery_product  p ON p.product_id  = pu.product_id;

CREATE OR REPLACE VIEW grocery_sale_v AS
SELECT sa.sale_id,
       sa.sale_date,
       c.customer_name,
       p.product_name,
       p.unit,
       sa.quantity,
       sa.selling_price,
       sa.total_amount,
       sa.quantity * (sa.selling_price - p.purchase_price) AS profit,
       sa.customer_id,
       sa.product_id
  FROM grocery_sale     sa
  JOIN grocery_customer c ON c.customer_id = sa.customer_id
  JOIN grocery_product  p ON p.product_id  = sa.product_id;

CREATE OR REPLACE VIEW grocery_daily_sales_v AS
SELECT TRUNC(sa.sale_date)                                 AS sale_day,
       COUNT(*)                                            AS no_of_sales,
       COUNT(DISTINCT sa.customer_id)                      AS no_of_customers,
       SUM(sa.quantity)                                    AS items_sold,
       SUM(sa.total_amount)                                AS total_sales,
       SUM(sa.quantity * (sa.selling_price - p.purchase_price)) AS total_profit
  FROM grocery_sale    sa
  JOIN grocery_product p ON p.product_id = sa.product_id
 GROUP BY TRUNC(sa.sale_date);


--------------------------------------------------------------------------------
-- SECTION 6 : SAMPLE DATA
-- Foreign keys are looked up by name, so the script never depends on
-- specific ID numbers.
--------------------------------------------------------------------------------

-- 6.1 Categories (5) ---------------------------------------------------------
INSERT INTO grocery_category (category_name, description) VALUES ('Grains and Pulses',   'Rice, flour, dal and other staples');
INSERT INTO grocery_category (category_name, description) VALUES ('Dairy Products',      'Milk, curd, paneer, butter');
INSERT INTO grocery_category (category_name, description) VALUES ('Beverages',           'Tea, coffee and drink mixes');
INSERT INTO grocery_category (category_name, description) VALUES ('Snacks and Biscuits', 'Biscuits, chips and namkeen');
INSERT INTO grocery_category (category_name, description) VALUES ('Cooking Essentials',  'Oil, sugar, salt and spices');

-- 6.2 Suppliers (5) ----------------------------------------------------------
INSERT INTO grocery_supplier (supplier_name, phone, email, address)
VALUES ('Kaveri Agro Traders',      '9840012345', 'sales@kaveriagro.example.com',   '12 Market Road, Koyambedu, Chennai');
INSERT INTO grocery_supplier (supplier_name, phone, email, address)
VALUES ('Sri Lakshmi Wholesale',    '9841123456', 'orders@srilakshmi.example.com',  '45 Mint Street, Sowcarpet, Chennai');
INSERT INTO grocery_supplier (supplier_name, phone, email, address)
VALUES ('Fresh Dairy Distributors', '9842234567', 'supply@freshdairy.example.com',  '8 Industrial Estate, Ambattur, Chennai');
INSERT INTO grocery_supplier (supplier_name, phone, email, address)
VALUES ('Metro FMCG Suppliers',     '9843345678', 'contact@metrofmcg.example.com',  '101 GST Road, Guindy, Chennai');
INSERT INTO grocery_supplier (supplier_name, phone, email, address)
VALUES ('Golden Oil Mills',         '9844456789', 'info@goldenoil.example.com',     '22 SIDCO Estate, Thirumudivakkam, Chennai');

-- 6.3 Customers (10) ---------------------------------------------------------
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Priya Raman',        '9500011111', 'priya.r@example.com',     'Anna Nagar, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Arun Kumar',         '9500022222', 'arun.k@example.com',      'T. Nagar, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Meena Subramanian',  '9500033333', 'meena.s@example.com',     'Adyar, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Karthik Rajan',      '9500044444', 'karthik.r@example.com',   'Velachery, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Divya Narayanan',    '9500055555', 'divya.n@example.com',     'Mylapore, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Suresh Babu',        '9500066666', NULL,                      'Tambaram, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Lakshmi Venkatesh',  '9500077777', 'lakshmi.v@example.com',   'Porur, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Rahul Menon',        '9500088888', 'rahul.m@example.com',     'Nungambakkam, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Anitha Joseph',      '9500099999', 'anitha.j@example.com',    'Perambur, Chennai');
INSERT INTO grocery_customer (customer_name, phone, email, address) VALUES ('Vijay Shankar',      '9500010101', 'vijay.s@example.com',     'Chromepet, Chennai');

-- 6.4 Products (10) - qty_in_stock here is the OPENING stock -----------------
INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Basmati Rice',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Grains and Pulses'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Kaveri Agro Traders'),
        'KG', 85, 110, 120, 30, DATE '2027-06-30');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Wheat Flour (Atta)',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Grains and Pulses'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Kaveri Agro Traders'),
        'KG', 38, 46, 80, 20, DATE '2026-12-31');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Toor Dal',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Grains and Pulses'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Sri Lakshmi Wholesale'),
        'KG', 120, 145, 18, 20, DATE '2027-04-30');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Toned Milk',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Dairy Products'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Fresh Dairy Distributors'),
        'LITRE', 44, 54, 40, 30, SYSDATE + 3);

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Paneer 200g',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Dairy Products'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Fresh Dairy Distributors'),
        'PACK', 70, 90, 15, 10, SYSDATE + 10);

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Tea Powder 250g',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Beverages'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Metro FMCG Suppliers'),
        'PACK', 110, 140, 50, 15, DATE '2027-08-31');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Instant Coffee 100g',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Beverages'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Metro FMCG Suppliers'),
        'PACK', 150, 190, 12, 15, DATE '2027-10-31');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Marie Biscuits',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Snacks and Biscuits'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Metro FMCG Suppliers'),
        'PACK', 25, 30, 200, 50, DATE '2027-01-31');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Sunflower Oil',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Cooking Essentials'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Golden Oil Mills'),
        'LITRE', 130, 155, 60, 20, DATE '2027-05-31');

INSERT INTO grocery_product (product_name, category_id, supplier_id, unit, purchase_price, selling_price, qty_in_stock, reorder_level, expiry_date)
VALUES ('Sugar',
        (SELECT category_id FROM grocery_category WHERE category_name = 'Cooking Essentials'),
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Sri Lakshmi Wholesale'),
        'KG', 40, 48, 100, 25, DATE '2027-03-31');

-- 6.5 Purchases (6) - price left empty, trigger copies it from the product ---
--     Each insert INCREASES stock automatically.
INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 10,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Kaveri Agro Traders'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Basmati Rice'), 50);

INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 9,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Fresh Dairy Distributors'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Toned Milk'), 30);

INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 8,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Metro FMCG Suppliers'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Marie Biscuits'), 100);

INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 6,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Golden Oil Mills'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Sunflower Oil'), 20);

INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 4,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Metro FMCG Suppliers'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Tea Powder 250g'), 20);

INSERT INTO grocery_purchase (purchase_date, supplier_id, product_id, quantity)
VALUES (SYSDATE - 3,
        (SELECT supplier_id FROM grocery_supplier WHERE supplier_name = 'Sri Lakshmi Wholesale'),
        (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Sugar'), 40);

-- 6.6 Sales (12) - each insert DECREASES stock automatically -----------------
INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 5, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Priya Raman'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Basmati Rice'), 5);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 5, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Arun Kumar'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Toned Milk'), 4);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 4, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Meena Subramanian'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Marie Biscuits'), 10);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 4, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Karthik Rajan'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Sunflower Oil'), 3);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 3, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Divya Narayanan'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Instant Coffee 100g'), 2);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 3, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Suresh Babu'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Sugar'), 5);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 2, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Lakshmi Venkatesh'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Tea Powder 250g'), 3);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 2, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Rahul Menon'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Toor Dal'), 3);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 1, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Anitha Joseph'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Paneer 200g'), 6);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE - 1, (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Vijay Shankar'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Wheat Flour (Atta)'), 4);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE,     (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Priya Raman'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Toned Milk'), 2);

INSERT INTO grocery_sale (sale_date, customer_id, product_id, quantity)
VALUES (SYSDATE,     (SELECT customer_id FROM grocery_customer WHERE customer_name = 'Karthik Rajan'),
                     (SELECT product_id  FROM grocery_product  WHERE product_name  = 'Marie Biscuits'), 6);

COMMIT;

--------------------------------------------------------------------------------
-- QUICK CHECK (run in SQL Commands after the script)
--   SELECT product_name, qty_in_stock, reorder_level, stock_status
--     FROM grocery_product_v ORDER BY product_name;
--
-- Expected LOW STOCK products after sample data:
--   Instant Coffee 100g (10 <= 15), Paneer 200g (9 <= 10), Toor Dal (15 <= 20)
--
-- Try the stock rule (should FAIL with ORA-20001 "Not enough stock"):
--   INSERT INTO grocery_sale (customer_id, product_id, quantity)
--   VALUES (1, (SELECT product_id FROM grocery_product
--               WHERE product_name = 'Instant Coffee 100g'), 500);
--------------------------------------------------------------------------------
